[versions]
kotlin = "2.3.10"
moshi = "1.15.2"

[libraries]
junit = { module = "junit:junit", version = "4.13.2" }
strikt = { module = "io.strikt:strikt-core", version = "0.34.1" }
robolectric = { module = "org.robolectric:robolectric", version = "4.16.1" }
androidx-test-junit = { module = "androidx.test.ext:junit", version = "1.3.0" }

moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }

kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.10.0" }

plugin-android = { module = "com.android.tools.build:gradle", version = "9.0.0" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
plugin-kover = { module = "org.jetbrains.kotlinx:kover-gradle-plugin", version = "0.9.6" }
plugin-maven-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version = "0.36.0" }

[plugins]
ksp = { id = "com.google.devtools.ksp", version = "2.3.6" }
